TITLE_1: 4300214
TITLE_2: Física Experimental IV
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |


GITHUB_LINK: https://github.com/Academic-Codex/IF4300214-Fisica-Experimental-IV

HERO_FILE: fisica-experimental-IV.png
